title: thom blog
description: a place for ideas
author: 
  name: thom krynen
  email: thom@gmx.com
remote_theme: jekyll/minima

social_links:
  github: kryn3n
  linkedin: tkrynen
  instagram: krynens

minima:
  date_format: "%b %-d, %Y"
  skin: solarized-light


header_pages:
  - about.md
