theme: minima
title: thom blog
description: a place for ideas
author: 
  name: thom krynen
  email: thom@gmx.com

base_url: /blog

github_username: kryn3n
linkedin_username: tkrynen
rss: rss

minima:
  date_format: "%Y-%m-%d"
  skin: solarized-dark

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
